//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Err {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Err() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Err", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사이트 설정이 올바르지 않습니다. 관리자에게 연락하세요.&lt;br /&gt;&lt;br /&gt;이용에 불편을 드려 죄송합니다...^_^.
        /// </summary>
        internal static string ERR_CONFIG_INVALID {
            get {
                return ResourceManager.GetString("ERR_CONFIG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자료기지조작중 오류가 발생하였습니다..
        /// </summary>
        internal static string ERR_DBERROR {
            get {
                return ResourceManager.GetString("ERR_DBERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그 아이디는 사용하실수 없습니다..
        /// </summary>
        internal static string ERR_LOGINID_CANNOTUSE {
            get {
                return ResourceManager.GetString("ERR_LOGINID_CANNOTUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디는 영문, 숫자로 4글자이상 10글자이하로 입력해주세요..
        /// </summary>
        internal static string ERR_LOGINID_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디를 입력하세요..
        /// </summary>
        internal static string ERR_LOGINID_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디가 이미 사용중입니다..
        /// </summary>
        internal static string ERR_LOGINID_INUSED {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디가 존재하지 않습니다. 확인해주세요..
        /// </summary>
        internal static string ERR_LOGINID_INVALID {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호가 일치하지 않습니다..
        /// </summary>
        internal static string ERR_LOGINPWDCONF_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWDCONF_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인용 비밀번호를 입력하세요..
        /// </summary>
        internal static string ERR_LOGINPWDCONF_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWDCONF_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호는 4글자이상 50글자이하로 입력해주세요..
        /// </summary>
        internal static string ERR_LOGINPWD_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호는 4글자이상 50글자이하로 입력해주세요..
        /// </summary>
        internal static string ERR_LOGINPWD_FORMAT1 {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_FORMAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 입력하세요..
        /// </summary>
        internal static string ERR_LOGINPWD_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 입력하세요..
        /// </summary>
        internal static string ERR_LOGINPWD_INPUT1 {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_INPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디나 비밀번호가 올바르지 않습니다..
        /// </summary>
        internal static string ERR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그 닉네임은 사용하실수 없습니다..
        /// </summary>
        internal static string ERR_NICKNAME_CANNOTUSE {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_CANNOTUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닉네임은 한글, 영문, 숫자로 3글자이상 10글자이하로 입력해주세요..
        /// </summary>
        internal static string ERR_NICKNAME_FORMAT {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닉네임을 입력하세요..
        /// </summary>
        internal static string ERR_NICKNAME_INPUT {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닉네임이 이미 사용중입니다..
        /// </summary>
        internal static string ERR_NICKNAME_INUSED {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_INUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 관리자권한을 가진 사용자만이 접근할수 있습니다..
        /// </summary>
        internal static string ERR_REQUIRED_ADMINAUTH {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_ADMINAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인하여주세요..
        /// </summary>
        internal static string ERR_REQUIRED_AUTH {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연락처는 XXX-XXXX-XXXX 또는 XXXXXXXXXXX의 형태로 입력해주세요..
        /// </summary>
        internal static string ERR_TELNO_FORMAT {
            get {
                return ResourceManager.GetString("ERR_TELNO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연락처를 입력하세요..
        /// </summary>
        internal static string ERR_TELNO_INPUT {
            get {
                return ResourceManager.GetString("ERR_TELNO_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원님은 접근이 차단되었습니다.\n차단일시: {0}.
        /// </summary>
        internal static string ERR_USER_INTERCEPT {
            get {
                return ResourceManager.GetString("ERR_USER_INTERCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원님의 데이터는 삭제되었습니다.\n삭제일시: {0}.
        /// </summary>
        internal static string ERR_USER_LEAVE {
            get {
                return ResourceManager.GetString("ERR_USER_LEAVE", resourceCulture);
            }
        }
    }
}
