//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Msg", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원님은 아이피 {0}으로부터 이미 로그인되어있습니다..
        /// </summary>
        internal static string MSG_ALEADYLOGIN {
            get {
                return ResourceManager.GetString("MSG_ALEADYLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API요청수가 초과되었습니다. 새 상품을 구입하셔야 합니다..
        /// </summary>
        internal static string MSG_APIREQUESTOVER {
            get {
                return ResourceManager.GetString("MSG_APIREQUESTOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일정시간동안 아무 조작도 하지 않았으므로 로그아웃되었습니다. 다시 로그인해주세요..
        /// </summary>
        internal static string MSG_AUTO_LOGOUT {
            get {
                return ResourceManager.GetString("MSG_AUTO_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 하드용량이 초과되었습니다. 일부 켐페인을 삭제하시거나 새 상품을 구입하셔야 합니다..
        /// </summary>
        internal static string MSG_HARDOVER {
            get {
                return ResourceManager.GetString("MSG_HARDOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마커 갯수가 초과되었습니다. 새 상품을 구입하셔야 합니다..
        /// </summary>
        internal static string MSG_MARKEROVER {
            get {
                return ResourceManager.GetString("MSG_MARKEROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원이 추가되었습니다..
        /// </summary>
        internal static string MSG_MEMBERJOIN {
            get {
                return ResourceManager.GetString("MSG_MEMBERJOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원정보가 수정되었습니다..
        /// </summary>
        internal static string MSG_MEMBERMODIFIED {
            get {
                return ResourceManager.GetString("MSG_MEMBERMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상품정보가 수정되었습니다..
        /// </summary>
        internal static string MSG_MODPRODUCT {
            get {
                return ResourceManager.GetString("MSG_MODPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제하실 항목을 선택해 주세요..
        /// </summary>
        internal static string MSG_NOSELECTITEM {
            get {
                return ResourceManager.GetString("MSG_NOSELECTITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공지사항이 수정되었습니다..
        /// </summary>
        internal static string MSG_NOTICEMODIFIED {
            get {
                return ResourceManager.GetString("MSG_NOTICEMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공지사항이 등록되었습니다..
        /// </summary>
        internal static string MSG_NOTICEREGISTERED {
            get {
                return ResourceManager.GetString("MSG_NOTICEREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상품이 추가되었습니다..
        /// </summary>
        internal static string MSG_PRODUCTREGISTERD {
            get {
                return ResourceManager.GetString("MSG_PRODUCTREGISTERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회원정보가 삭제되었습니다..
        /// </summary>
        internal static string MSG_REMOVEUSEROK {
            get {
                return ResourceManager.GetString("MSG_REMOVEUSEROK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 트래픽용량이 초과되었습니다. 새 상품을 구입하셔야 합니다. 관리자에게 문의해주십시오..
        /// </summary>
        internal static string MSG_TRAFFICOVER {
            get {
                return ResourceManager.GetString("MSG_TRAFFICOVER", resourceCulture);
            }
        }
    }
}
